name: toeic
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-44.1.beta <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # Dependency Injection
  injectable: ^1.5.3
  get_it: ^7.2.0
  # Bloc
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

  # Generate Immutable Class

  # Stream and StreamController
  rxdart: ^0.27.4
  # Api
  http: ^0.13.4
  dio: ^4.0.6
  retrofit: '>=3.0.0 <4.0.0'
  # Logger
  logger: ^1.1.0
  # Image
  flutter_svg: ^1.1.0
  cached_network_image: ^3.2.1
  octo_image: ^1.0.2
  # Format
  intl: ^0.17.0
  # Database
  sqflite: ^2.0.2+1
  # Font
  google_fonts: ^3.0.1
  # Permission Handler
  permission_handler: ^9.2.0
  # Animations
  animations: ^2.0.3
  # Handle environment variable
  #  envify: ^2.0.2
  # Notification
  flutter_local_notifications: ^12.0.4
  # Toast
  fluttertoast: ^8.0.9
  # Loading no context
  flutter_easyloading: ^3.0.5
  #carousel_slider
  carousel_slider: ^4.1.1
  #For schedule
  table_calendar: ^3.0.6
  timelines: ^0.1.0
  fl_chart: ^0.55.0
  expandable: ^5.0.1
  shimmer: ^2.0.0

  # Icons
  flutter_icons: ^1.1.0
  # Localization
  easy_localization: ^3.0.1
  # Analyzer
  #  analyzer: ^4.1.0
  # Url
  url_launcher:

  hive: ^2.2.2
  hive_flutter: ^1.1.0

  # FingerPrint
  local_auth: ^2.1.0
  firebase_auth: ^3.3.20
  google_sign_in: ^5.3.3
  firebase_core: ^1.18.0
  loading_indicator: ^3.0.3
  email_validator: ^2.0.1
  flutter_countdown_timer: ^4.1.0
  pin_code_fields: ^7.4.0

  flutter_holo_date_picker: ^1.0.3
  r_dotted_line_border: ^0.1.1
  mime_type: ^1.0.0
  image_picker: ^0.8.5+3
  freezed_annotation: ^2.0.3

  firebase_messaging: any
  awesome_notifications: ^0.6.21
  envify: ^2.0.2
  splashscreen: ^1.3.5
  flutter_native_splash: ^2.2.9
  firebase_storage: ^10.3.11
  bottom_navy_bar: ^6.0.0
  audioplayers: ^1.1.1
  flutter_html: ^3.0.0-alpha.6
  flutter_heatmap_calendar: ^1.0.5
  flutter_radar_chart: ^0.2.1
  flutter_native_timezone: ^2.0.0
  dropdown_search: ^5.0.3
  sleek_circular_slider: ^2.0.1
  animated_text_kit: ^4.2.2
  flutter_charts: ^0.4.0
  d_chart: ^1.0.0
  showcaseview: ^2.0.0+1
  photo_view: ^0.14.0
  floor: ^1.0.0-nullsafety.0
  flutter_downloader: ^1.9.1
  path_provider: ^2.0.11
  flutter_archive: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.3

  retrofit_generator: '>=4.0.0 <5.0.0'
  json_serializable: '>4.4.0'

  hive_generator: ^1.1.3
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"
  floor_generator: ^1.0.0-nullsafety.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
